"""Task 4 - Markdown-aware chunking, embedding, and ChromaDB indexing.

The corpus mixes structured Markdown generated by Role 2 with legacy plain
Markdown converted from teammate TXT files.  The pipeline therefore uses two
stages:

1. ``MarkdownHeaderTextSplitter`` keeps headings as section context.
2. ``RecursiveCharacterTextSplitter`` enforces a predictable upper bound and
   overlap for long sections.

Why this chunking strategy:
    - Travel/legal documents are naturally hierarchical: city -> activity ->
      food/transport/safety. Splitting by Markdown headers keeps that section
      meaning attached to every chunk, so citations still know where the answer
      came from.
    - Recursive character splitting is added after header splitting because
      some sections are still too long for retrieval and LLM context. A stable
      size and overlap improves recall without duplicating too much content.

Why OpenAI embeddings:
    - The corpus is mixed Vietnamese and English, and user questions may also
      be bilingual. OpenAI embedding models handle multilingual semantic
      matching well without downloading a large local model.
    - Using OpenAI avoids the local ``sentence_transformers`` dependency and
      lets teammates reproduce indexing with only ``OPENAI_API_KEY`` in ``.env``.

Why ChromaDB:
    - Chroma is local and persistent, which fits a student RAG project: no
      external vector database account, easy reruns, and enough metadata
      filtering/citation support for this corpus size.

Run from the repository root::

    python -m src.task4_chunking_indexing
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import unicodedata
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

from dotenv import load_dotenv


PROJECT_DIR = Path(__file__).resolve().parent.parent
load_dotenv(PROJECT_DIR / ".env")

STANDARDIZED_DIR = PROJECT_DIR / "data" / "standardized"
CHROMA_DIR = PROJECT_DIR / "chroma_db"

# Chunking choice:
# - 1000 characters keeps chunks small enough for precise retrieval/citation,
#   but large enough to contain a complete travel tip or legal/policy rule.
# - 120 characters overlap protects facts that sit on a boundary between
#   adjacent chunks, especially itinerary steps and transport/safety notes.
# LangChain's default length function and the lab tests measure characters.
CHUNK_SIZE = 1000
CHUNK_OVERLAP = 120
CHUNKING_METHOD = "markdown_header+recursive"

# Embedding choice:
# OpenAI keeps indexing lightweight for the team: no local transformer download,
# no GPU/CPU model setup, and the key is read from .env as OPENAI_API_KEY.
EMBEDDING_PROVIDER = "openai"
EMBEDDING_MODEL = os.getenv("OPENAI_EMBEDDING_MODEL", "text-embedding-3-small")
_OPENAI_EMBEDDING_DIMS = {
    "text-embedding-3-small": 1536,
    "text-embedding-3-large": 3072,
    "text-embedding-ada-002": 1536,
}
EMBEDDING_DIM = int(
    os.getenv(
        "OPENAI_EMBEDDING_DIM",
        str(_OPENAI_EMBEDDING_DIMS.get(EMBEDDING_MODEL, 1536)),
    )
)

# Vector-store choice:
# ChromaDB keeps the index local and reproducible for the lab, while storing
# metadata such as source/title/location that downstream citation needs.
VECTOR_STORE = "chromadb"
COLLECTION_NAME = os.getenv("CHROMA_COLLECTION_NAME", "smart_travel_docs_openai")
INDEX_BATCH_SIZE = 256

HEADERS_TO_SPLIT_ON = [
    ("#", "h1"),
    ("##", "h2"),
    ("###", "h3"),
    ("####", "h4"),
]


def _normalise_text(value: str) -> str:
    value = unicodedata.normalize("NFD", value.casefold())
    value = "".join(char for char in value if unicodedata.category(char) != "Mn")
    return re.sub(r"\s+", " ", value).strip()


def _parse_front_matter(content: str) -> tuple[dict[str, Any], str]:
    """Parse the JSON-compatible YAML front matter emitted by Task 3."""

    if not content.startswith("---\n"):
        return {}, content
    end = content.find("\n---\n", 4)
    if end == -1:
        return {}, content

    metadata: dict[str, Any] = {}
    for line in content[4:end].splitlines():
        if ":" not in line:
            continue
        key, raw_value = line.split(":", 1)
        raw_value = raw_value.strip()
        try:
            metadata[key.strip()] = json.loads(raw_value)
        except json.JSONDecodeError:
            metadata[key.strip()] = raw_value.strip("\"'")
    return metadata, content[end + 5 :].lstrip()


def _infer_location(path: Path, content: str, metadata: dict[str, Any]) -> str:
    if metadata.get("location"):
        return str(metadata["location"])

    path_searchable = _normalise_text(re.sub(r"[_-]+", " ", path.stem))
    locations = (
        (("ha giang", "hagiang"), "Hà Giang"),
        (("ha noi", "hanoi"), "Hà Nội"),
        (("da nang", "danang"), "Đà Nẵng"),
        (("da lat", "dalat"), "Đà Lạt"),
        (("nha trang", "nhatrang"), "Nha Trang"),
        (("quy nhon", "quynhon"), "Quy Nhơn"),
        (("hoi an", "hoian"), "Hội An"),
        (("phong nha", "phongnha"), "Phong Nha"),
        (("mui ne", "muine"), "Mũi Né"),
    )
    for markers, display in locations:
        if any(marker in path_searchable for marker in markers):
            return display

    searchable = _normalise_text(content[:1500])
    matches = [
        display
        for markers, display in locations
        if any(marker in searchable for marker in markers)
    ]
    return ", ".join(matches) if matches else "Việt Nam"


def _normalise_category(metadata: dict[str, Any], doc_type: str, text: str) -> str:
    categories = metadata.get("categories", [])
    if isinstance(categories, str):
        categories = [categories]
    searchable = _normalise_text(" ".join(map(str, categories)) + " " + text[:600])

    category_markers = (
        (("lich trinh", "itinerary", "ngay 1", "day 1"), "itinerary"),
        (("am thuc", "mon an", "food", "cuisine", "restaurant"), "food"),
        (("van hoa", "ung xu", "culture", "etiquette"), "culture_etiquette"),
        (("chi phi", "tiet kiem", "budget", "cost", "price"), "budget"),
        (("an toan", "safety"), "safety"),
    )
    for markers, category in category_markers:
        if any(marker in searchable for marker in markers):
            return category
    if doc_type == "legal":
        return "legal_policy" if "luat" in searchable else "travel_guide"
    return "travel_guide"


def _chunk_category(text: str, fallback: str) -> str:
    """Assign a focused category to a chunk instead of a whole long guide."""

    searchable = _normalise_text(text)
    category_markers = (
        (
            (
                "am thuc",
                "mon an",
                "dac san",
                "quan an",
                "thuong thuc",
                "banh ",
                "bun ",
                "pho ",
                "hai san",
                "food",
                "cuisine",
                "restaurant",
            ),
            "food",
        ),
        (("van hoa", "ung xu", "phong tuc", "culture", "etiquette"), "culture_etiquette"),
        (("chi phi", "tiet kiem", "ngan sach", "budget", "cost", "price"), "budget"),
        (("an toan", "canh bao", "safety"), "safety"),
        (
            (
                "lich trinh",
                "ngay 1",
                "ngay 2",
                "ngay 3",
                "buoi sang",
                "buoi trua",
                "buoi toi",
                "xe may",
                "thue xe",
                "cung duong",
                "itinerary",
                "day 1",
            ),
            "itinerary",
        ),
    )
    for markers, category in category_markers:
        if any(marker in searchable for marker in markers):
            return category
    return fallback


def _extract_title(content: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", content, flags=re.MULTILINE)
    return match.group(1).strip() if match else fallback


def _metadata_year(metadata: dict[str, Any]) -> int:
    for key in ("year", "date_crawled", "published_at"):
        value = str(metadata.get(key, ""))
        match = re.match(r"(19|20)\d{2}", value)
        if match:
            return int(match.group(0))
    return datetime.now(timezone.utc).year


def _scalar_metadata(metadata: dict[str, Any]) -> dict[str, str | int | float | bool]:
    """Convert values to scalar types accepted by every ChromaDB version."""

    result: dict[str, str | int | float | bool] = {}
    for key, value in metadata.items():
        if value is None:
            continue
        if isinstance(value, (str, int, float, bool)):
            result[key] = value
        else:
            result[key] = json.dumps(value, ensure_ascii=False)
    return result


def load_documents() -> list[dict]:
    """Load all standardised Markdown files with retrieval-ready metadata."""

    if not STANDARDIZED_DIR.exists():
        return []

    documents: list[dict] = []
    for md_file in sorted(STANDARDIZED_DIR.rglob("*.md")):
        raw_content = md_file.read_text(encoding="utf-8").strip()
        if not raw_content:
            continue
        front_matter, content = _parse_front_matter(raw_content)
        doc_type = "legal" if "legal" in md_file.parts else "news"
        relative_path = md_file.relative_to(PROJECT_DIR).as_posix()
        source = str(front_matter.get("source") or relative_path)
        title = str(front_matter.get("title") or _extract_title(content, md_file.stem))
        metadata = {
            "source": source,
            "source_path": relative_path,
            "title": title,
            "location": _infer_location(md_file, content, front_matter),
            "category": _normalise_category(front_matter, doc_type, content),
            "year": _metadata_year(front_matter),
            "doc_type": doc_type,
            "language": str(front_matter.get("language") or "vi"),
        }
        if front_matter.get("source_name"):
            metadata["source_name"] = str(front_matter["source_name"])
        documents.append({"content": content, "metadata": metadata})
    return documents


def chunk_documents(documents: list[dict]) -> list[dict]:
    """Split documents by Markdown headings, then enforce size and overlap."""

    try:
        from langchain_text_splitters import (
            MarkdownHeaderTextSplitter,
            RecursiveCharacterTextSplitter,
        )

        header_splitter = MarkdownHeaderTextSplitter(
            headers_to_split_on=HEADERS_TO_SPLIT_ON,
            strip_headers=False,
        )
        size_splitter = RecursiveCharacterTextSplitter(
            chunk_size=CHUNK_SIZE,
            chunk_overlap=CHUNK_OVERLAP,
            separators=["\n\n", "\n", ". ", "; ", ", ", " ", ""],
            keep_separator=True,
            length_function=len,
        )
    except ImportError:
        # Fallback if langchain_text_splitters is not installed
        chunks: list[dict] = []
        for document_index, document in enumerate(documents):
            content = document.get("content", "")
            step = CHUNK_SIZE - CHUNK_OVERLAP
            for start in range(0, max(1, len(content)), step):
                chunk_text = content[start:start + CHUNK_SIZE].strip()
                if chunk_text:
                    chunks.append({
                        "content": chunk_text,
                        "metadata": {
                            **_scalar_metadata(document.get("metadata", {})),
                            "document_index": document_index,
                            "chunk_index": len(chunks),
                            "section": str(document.get("metadata", {}).get("title", "document"))
                        }
                    })
        return chunks


    chunks: list[dict] = []
    for document_index, document in enumerate(documents):
        sections = header_splitter.split_text(document["content"])
        section_payloads = [
            (section.page_content, section.metadata) for section in sections
        ] or [(document["content"], {})]

        document_chunks: list[dict] = []
        for section_index, (section_content, section_metadata) in enumerate(
            section_payloads
        ):
            header_values = [
                str(section_metadata[key])
                for key in ("h1", "h2", "h3", "h4")
                if section_metadata.get(key)
            ]
            section_name = " > ".join(header_values) or str(document["metadata"]["title"])
            for text in size_splitter.split_text(section_content):
                clean_text = text.strip()
                if not clean_text:
                    continue
                document_chunks.append(
                    {
                        "content": clean_text,
                        "metadata": {
                            **document["metadata"],
                            "category": _chunk_category(
                                clean_text, str(document["metadata"]["category"])
                            ),
                            "document_index": document_index,
                            "section_index": section_index,
                            "section": section_name,
                        },
                    }
                )

        for chunk_index, chunk in enumerate(document_chunks):
            chunk["metadata"]["chunk_index"] = chunk_index
            chunk["metadata"] = _scalar_metadata(chunk["metadata"])
            chunks.append(chunk)
    return chunks


def get_embedding_provider() -> str:
    """Return the selected provider and require OpenAI for this pipeline."""

    provider = (
        os.getenv("EMBEDDING_PROVIDER", EMBEDDING_PROVIDER)
        .split("#", 1)[0]
        .strip()
        .lower()
    )
    aliases = {"openai-api": "openai"}
    provider = aliases.get(provider, provider)
    if provider != "openai":
        raise ValueError(
            "Task 4 is configured for OpenAI embeddings. Set "
            "EMBEDDING_PROVIDER=openai and OPENAI_API_KEY in .env before indexing."
        )
    return provider


def get_embedding_model():
    """Create an OpenAI client lazily so chunk-only tests stay fast."""

    get_embedding_provider()
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise ValueError("Thiếu OPENAI_API_KEY trong .env để tạo embeddings.")

    from openai import OpenAI

    return OpenAI(api_key=api_key)


def embed_texts(texts: list[str], *, show_progress: bool = False) -> list[list[float]]:
    """Embed texts with OpenAI dense vectors."""

    if not texts:
        return []
    client = get_embedding_model()
    batch_size = int(os.getenv("EMBEDDING_BATCH_SIZE", "64"))
    embeddings: list[list[float]] = []
    total = len(texts)
    for start in range(0, total, batch_size):
        batch = texts[start : start + batch_size]
        if show_progress:
            print(f"  Embedding batch {start + 1}-{start + len(batch)}/{total}")
        response = client.embeddings.create(
            model=EMBEDDING_MODEL,
            input=batch,
        )
        embeddings.extend(item.embedding for item in response.data)
    if embeddings and len(embeddings[0]) != EMBEDDING_DIM:
        raise ValueError(
            f"Embedding dimension mismatch: expected {EMBEDDING_DIM}, "
            f"received {len(embeddings[0])}"
        )
    return embeddings


def embed_chunks(chunks: list[dict]) -> list[dict]:
    """Return chunks with OpenAI dense embeddings."""

    embeddings = embed_texts(
        [chunk["content"] for chunk in chunks], show_progress=True
    )
    return [
        {**chunk, "embedding": embedding}
        for chunk, embedding in zip(chunks, embeddings)
    ]


def get_chroma_client():
    import chromadb

    CHROMA_DIR.mkdir(parents=True, exist_ok=True)
    return chromadb.PersistentClient(path=str(CHROMA_DIR))


def get_collection(*, create: bool = True):
    """Open the cosine collection used by both indexing and search."""

    client = get_chroma_client()
    if not create:
        return client.get_collection(COLLECTION_NAME)
    descriptive_metadata = {
        "embedding_model": EMBEDDING_MODEL,
        "embedding_dimension": EMBEDDING_DIM,
        "chunking_method": CHUNKING_METHOD,
        "chunk_size": CHUNK_SIZE,
        "chunk_overlap": CHUNK_OVERLAP,
    }
    existing_names = {collection.name for collection in client.list_collections()}
    if COLLECTION_NAME not in existing_names:
        return client.create_collection(
            name=COLLECTION_NAME,
            metadata={"hnsw:space": "cosine", **descriptive_metadata},
        )

    collection = client.get_collection(COLLECTION_NAME)
    current_metadata = dict(collection.metadata or {})
    mutable_metadata = {
        key: value for key, value in current_metadata.items() if key != "hnsw:space"
    }
    if any(mutable_metadata.get(key) != value for key, value in descriptive_metadata.items()):
        collection.modify(metadata={**mutable_metadata, **descriptive_metadata})
    return collection


def _chunk_id(chunk: dict) -> str:
    metadata = chunk["metadata"]
    identity = (
        f"{metadata.get('source_path', metadata.get('source', 'unknown'))}:"
        f"{metadata.get('chunk_index', 0)}:{chunk['content']}"
    )
    return hashlib.sha256(identity.encode("utf-8")).hexdigest()[:32]


def _batched(items: list[Any], size: int) -> Iterable[list[Any]]:
    for start in range(0, len(items), size):
        yield items[start : start + size]


def index_to_vectorstore(chunks: list[dict]):
    """Upsert current chunks and remove stale chunks from earlier corpus runs."""

    collection = get_collection(create=True)
    ids = [_chunk_id(chunk) for chunk in chunks]
    for batch_indices in _batched(list(range(len(chunks))), INDEX_BATCH_SIZE):
        collection.upsert(
            ids=[ids[index] for index in batch_indices],
            documents=[chunks[index]["content"] for index in batch_indices],
            embeddings=[chunks[index]["embedding"] for index in batch_indices],
            metadatas=[chunks[index]["metadata"] for index in batch_indices],
        )

    existing_ids = set(collection.get(include=[])["ids"])
    stale_ids = sorted(existing_ids - set(ids))
    for batch in _batched(stale_ids, INDEX_BATCH_SIZE):
        collection.delete(ids=batch)
    return collection


def run_pipeline() -> dict[str, int]:
    """Run load -> chunk -> embed -> index and return checkpoint statistics."""

    print("=" * 60)
    print("Task 4: Chunking & Indexing")
    print(f"  Chunking: {CHUNKING_METHOD} (size={CHUNK_SIZE}, overlap={CHUNK_OVERLAP})")
    print(f"  Embedding: {EMBEDDING_MODEL} (dim={EMBEDDING_DIM})")
    print(f"  Vector Store: {VECTOR_STORE}/{COLLECTION_NAME}")
    print("=" * 60)

    documents = load_documents()
    if not documents:
        raise RuntimeError(f"Không tìm thấy Markdown trong {STANDARDIZED_DIR}")
    print(f"\n✓ Loaded {len(documents)} documents")

    chunks = chunk_documents(documents)
    if not chunks:
        raise RuntimeError("Chunking không tạo ra chunk nào")
    print(f"✓ Created {len(chunks)} chunks")

    embedded_chunks = embed_chunks(chunks)
    print(f"✓ Embedded {len(embedded_chunks)} chunks")

    collection = index_to_vectorstore(embedded_chunks)
    count = collection.count()
    print(f"✓ Indexed {count} chunks to {CHROMA_DIR}")
    return {"documents": len(documents), "chunks": len(chunks), "indexed": count}


if __name__ == "__main__":
    run_pipeline()
